name: Conventional Label

on:
  pull_request:
    types: [opened, synchronize, edited]

jobs:
  conventional_label:
    uses: OpenVoiceOS/gh-automations/.github/workflows/conventional-label.yaml@dev
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      MATRIX_TOKEN: ${{ secrets.MATRIX_TOKEN }}
