name: pip audit

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  pip_audit:
    uses: OpenVoiceOS/gh-automations/.github/workflows/pip_audit.yml@dev
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      MATRIX_TOKEN: ${{ secrets.MATRIX_TOKEN }}
