name: Publish Stable Release

on:
  push:
    branches:
      - master

jobs:
  publish_stable:
    uses: OpenVoiceOS/gh-automations/.github/workflows/publish_stable.yml@dev
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      MATRIX_TOKEN: ${{ secrets.MATRIX_TOKEN }}
