name: Release Alpha

on:
  push:
    branches:
      - dev

jobs:
  release_alpha:
    uses: OpenVoiceOS/gh-automations/.github/workflows/publish-alpha.yml@dev
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      MATRIX_TOKEN: ${{ secrets.MATRIX_TOKEN }}
    with:
      version_file: nuvem_de_som/version.py
      package_name: nuvem_de_som
